#1: Extracted database cleaner from exasol-testcontainers
exasol/database-cleaner pull request #2
Opened 2021-03-05 18:08 UTC by jakobbraun

Closes #1

2021-03-05 18:20 UTC, jakobbraun commented
CI fails because of the docker rate limit. Needs a restart on moday

2021-03-07 18:25 UTC, morazow requested changes

2021-03-07 18:25 UTC, morazow commented on LICENSE
> +Copyright (c) 2020 Exasol
```suggestion
Copyright (c) 2021 Exasol
```

2021-03-07 18:25 UTC, morazow commented on README.md
> +# @formatter:off
Remove these.

You can use html commenting `<!--  -->` in markdown if you need. But I think you can just remove them.

2021-03-07 18:25 UTC, morazow commented on doc/changes/changelog.md
> +* [0.1.0](changes_0.1.0.md)
```suggestion
* [1.0.0](changes_1.0.0.md)
```

2021-03-07 18:25 UTC, morazow commented on pom.xml
> +    <description>Tool that deletes all object in an Exasol database
```suggestion
    <description>Tool that deletes all objects in an Exasol database
```

2021-03-07 18:27 UTC, morazow commented
So this is the part Sebastian was mentioning in the channel! Thanks, this looks great!

2021-03-08 07:58 UTC, morazow approved these changes

2021-03-08 08:35 UTC, merged